version: "3.7"

services:

  postgresql:
    container_name: "postgresql_smenatest"
    image: postgres:9.6
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "smenauser"
      POSTGRES_PASSWORD: "smenaqwe"
      POSTGRES_DB: "smena"
    volumes:
      - ./database-data:/var/lib/postgresql/data

  redis:
    container_name: "redis_smena"
    image: redis
    restart: always
    ports:
      - "6379:6379"

  wkhtmltopdf:
    container_name: "wkhtmltopdf_smena"
    image: openlabs/docker-wkhtmltopdf-aas
    restart: always
    ports:
      - "8001:80"

volumes:
  database-data: